import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/style/globals.scss";

import Header from "@/components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  const menuItems = [
    { label: "Nosotros", href: "/nosotros" },
    { label: "Catálogo", href: "/catalogo" },
    { label: "Contacto", href: "/contacto" },
  ]

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header menuItems={menuItems} />
        {children}
        <footer className='footer'></footer>
      </body>
    </html>
  );
}
